import initRoute from './api/init';
import wechatRoute from './api/wechat';
import usersRoute from './api/users';
import hospitalsRoute from './api/hospitals';
import doctorRoute from './api/doctor';
import arrangementHistoryRoute from './api/arrangementHistory';
import registerHistoryRoute from './api/registerHistory';
import visitorRoute from './api/visitor';
import department1 from './api/department1';
import department2 from './api/department2';
import hospitalAdmin from './api/hospitalAdmin';
import patientRoute from './api/patient';
import supplierRoute from './api/supplier';
import medicalItemsRoute from './api/medicalItems';
import prescriptionRoute from './api/prescription';
import caseItemRoute from './api/caseItem';
import orderRoute from './api/order';
import orderItemRoute from './api/orderItem';
import paymentHistoryRoute from './api/paymentHistory';
import outboundHistoryRoute from './api/outboundHistory';

export default function (app) {
  app.use('/init', initRoute);
  app.use('/auth/wechat', wechatRoute);
  app.use('/auth/users', usersRoute);
  app.use('/hospital', hospitalsRoute);
  app.use('/doctor', doctorRoute);
  app.use('/arrangement_history', arrangementHistoryRoute);
  app.use('/register_history', registerHistoryRoute);
  app.use('/visitor', visitorRoute);
  app.use('/department1', department1);
  app.use('/department2', department2);
  app.use('/hospital_admin', hospitalAdmin);
  app.use('/patient', patientRoute);
  app.use('/supplier', supplierRoute);
  app.use('/medicalItems', medicalItemsRoute);
  app.use('/prescription', prescriptionRoute);
  app.use('/caseItem', caseItemRoute);
  app.use('/order', orderRoute);
  app.use('/orderItem', orderItemRoute);
  app.use('/paymentHistory', paymentHistoryRoute);
  app.use('/outboundHistory', outboundHistoryRoute);
}
